image:
  repository: jellyfin/jellyfin
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8096

persistence:
  config:
    enabled: true
    storageClass: "local-path"  # o "standard", o la que tengas
    accessMode: ReadWriteOnce
    size: 5Gi
